services:
  server:
    image: gitea/gitea:1.22.0-rootless
    restart: always
    volumes:
      - ./container/data:/var/lib/gitea
      - ./container/config:/etc/gitea
      - ./container/etc/timezone:/etc/timezone:ro
      - ./container/etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"