services: 
    postgres:
        image: postgres
        volumes:
            - ./volume:/config:rw
            - ./volume/backup:/backup
        ports:
            - "5432:5432"
        environment:
          POSTGRES_DB: MyDatabase
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        command: "postgres"
    pgadmin:
        image: elestio/pgadmin
        ports:
            - "8080:8080"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_LISTEN_PORT: 8080
        volumes:
            - ./volume/pgadmin:/dbs:rw
            - ./volume/pgadmin:/var/lib/pgadmin/storage